CC      = gcc
CFLAGS  = -Wall -g0 -O3 -DENV_QNX -D_REENTRANT -DOAPC_EXT_API="" -D_DEBUG -L/usr/lib -L/usr/local/lib/ -L/opt/X11R6/lib/ -I/usr/local/include

LDFLAGS  = -lsocket -lwlocate

PNAME=geolocation.cgi

OBJ = JSON_parser.o main.o
SRC = JSON_parser.c main.c

all: $(OBJ)
	$(CC) $(CFLAGS) -o $(PNAME) $(OBJ) $(LDFLAGS)
	strip $(PNAME)

clean:
	rm *.o
	rm $(PNAME)
